norm_diff_threshold: 0.25
heatmap_vis_upper_bound: 0.75
blend_weight_original_image: 0.3
# randomize_images: False
randomize_images: True
same_object: True
different_objects: False
multiple_object: False # sample from multi object scenes
kernel_variance: 0.25
networks:
# - "carla_3"
- "carla_32"

pickle_folder:
- "/projects/katefgroup/datasets/shamit_carla_correct/npys/mc_don"

do_pca: True

hardcode_samples: True
scene_name_1_list:
- "15885529876821635"
- "15885530311595225"
scene_name_2_list:
- "15885529942093484"
- "15885537448825345"
image_1_idx_list:
- 11
- 6
image_2_idx_list:
- 13
- 7
norm_diff_threshold_dict:
  hats_consistent_M_background_0.500_3:
    0.25
  hats_specific_M_background_2.000_9:
    0.35
  shoes_specific_M_background_2.000_6_with_synthetic:
    0.35