params:
  num_image_pairs: 25
  num_matches_per_image_pair: 100

networks:
  carla_3:
    path_to_network_params: trained_models/tutorials/carla_3/003501.pth
  carla_32:
    path_to_network_params: trained_models/tutorials/carla_32/005501.pth

dataset: [] # which dataset to use, not used for now

output_dir: analysis

pickle_folder:
- "/projects/katefgroup/datasets/shamit_carla_correct/npys/mc_don"