logs_root_path: logs_proto

single_object_scenes_config_files:
- carla_4cars_train.yaml

multi_object_scenes_config_files: []

pickle_folder:
- "/projects/katefgroup/datasets/shamit_carla_correct/npys/mc_don"